- name: Set timezone
  community.general.timezone:
    name: UTC
- name: 'Create data directory'
  ansible.builtin.file:
    path: /data
    mode: '0755'
    state: directory
    owner: 'root'
    group: 'root'
- name: 'Copy measurement requirements'
  ansible.builtin.copy:
    src: files/qscanner/
    dest: '{{ qscanner_dir }}'
    mode: '0755'
- name: 'Install required software'
  ansible.builtin.apt:
    update_cache: true
    name:
      - python3
      - python-is-python3
      - python3-pip
      - tmux
      - jq
      - pcaputils
      - wireshark-common
      - bmon
- name: 'Install required python modules'
  ansible.builtin.pip:
    name: pandas
- name: Add control ssh key
  authorized_key:
    user: "{{ ansible_user }}"
    key: "ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBNXfjYPTyWFr0I15EiMKyNMU71I8ro6ax4X/pBMi+0na9+DW0PvFwUrHx3Y/tthVxIlMZplSDzm2kMeHLk3JpNI= jonas@vm-172-26-122-167.rc.test.tu-dresden.de"
